# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurveyHelplinePro
                                 A QGIS plugin
 Toolset for Survey team related to GIS works
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-29
        copyright            : (C) 2025 by Batchu Pramod Kumar
        email                : bpramod29@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SurveyHelplinePro class from file SurveyHelplinePro.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .survey_helpline_pro import SurveyHelplinePro
    return SurveyHelplinePro(iface)
